Rewrite ddns-up script.

diff --git a/ddns-up b/ddns-up
--- a/ddns-up
+++ b/ddns-up
@@ -1,62 +1,39 @@
-#!/usr/bin/env python
-#-*- coding:utf-8 -*-
+#!/bin/bash
 
-import httplib, urllib
-import socket
-import time
-import os
-import sys
+PIDFILE=/var/run/ddns.pid
+LOGFILE=/var/log/ddns-up.log
+LOGIN=
+PASS=
+FORMAT="json"
+DOMID=
+RECID=
+SUBDOM=
+RECLINE="默认"
+INTERVAL="120"
 
-pid = str(os.getpid())
-pidfile = "/tmp/ddns.pid"
+if [ -f /var/run/ddns.pid ]; then
+  echo "$(date "+%Y-%m-%d %H:%M:%S") - PID file exists. Checking for running process." | tee -a $LOGFILE
+  ps up $(cat $PIDFILE) &> /dev/null
+  if [ $? -ne 0 ]; then
+    echo "$(date "+%Y-%m-%d %H:%M:%S") - PID is stale. Remove and restarting." | tee -a $LOGFILE
+    rm $PIDFILE
+    echo $$ > $PIDFILE
+  else
+    echo "$(date "+%Y-%m-%d %H:%M:%S") - Process is still up and running. Script aborted." | tee -a $LOGFILE
+  fi
+else
+  echo $$ > $PIDFILE
+fi
 
-if os.path.isfile(pidfile):
-    print "%s already exists, exiting" % pidfile
-    sys.exit()
-else:
-    file(pidfile, 'w').write(pid)
-
-params = dict(
-    login_email="", # replace with your email
-    login_password="", # replace with your password
-    format="json",
-    domain_id=, # replace with your domain_od, can get it by API Domain.List
-    record_id=, # replace with your record_id, can get it by API Record.List
-    sub_domain="", # replace with your sub_domain
-    record_line="默认",
-    )
-current_ip = None
-
-def ddns(ip):
-    params.update(dict(value=ip))
-    headers = {"Content-type": "application/x-www-form-urlencoded", "Accept": "text/json"}
-    conn = httplib.HTTPSConnection("dnsapi.cn")
-    conn.request("POST", "/Record.Ddns", urllib.urlencode(params), headers)
-
-    response = conn.getresponse()
-    print response.status, response.reason
-    data = response.read()
-    print data
-    conn.close()
-    return response.status == 200
-
-def getip():
-    sock = socket.create_connection(('ns1.dnspod.net', 6666))
-    ip = sock.recv(16)
-    sock.close()
-    return ip
-
-if __name__ == '__main__':
-    while True:
-        try:
-            ip = getip()
-            print ip
-            if current_ip != ip:
-                if ddns(ip):
-                    current_ip = ip
-        except Exception, e:
-            print e
-            pass
-        time.sleep(30)
-
-os.unlink(pidfile)
+while true; do
+  MYIP=$(curl --silent -X POST http://cynovan.com/ip.php | tr -d "\n")
+  DOMIP=$(curl --silent -X POST https://dnsapi.cn/Record.Info -d "login_email=$LOGIN&login_password=$PASS&format=$FORMAT&domain_id=$DOMID&record_id=$RECID" | python -mjson.tool | grep value | cut -d: -f2 | tr -d "\"" | tr -d " ")
+  if [ $MYIP = $DOMIP ]; then
+    echo "IP not changed: $MYIP. Sleeping for 30 seconds." | tee -a $LOGFILE
+    sleep $INTERVAL
+  else
+    echo "IP change detected. Original: $DOMIP -- Updating to: $MYIP " | tee -a $LOGFILE
+    curl --silent -X POST https://dnsapi.cn/Record.Ddns -d "login_email=$LOGIN&login_password=$PASS&format=$FORMAT&domain_id=$DOMID&record_id=$RECID&record_line=$RECLINE&sub_domain=$SUBDOM"
+    sleep $INTERVAL
+  fi
+done
