add notify-send

diff --git a/makenow b/makenow
--- a/makenow
+++ b/makenow
@@ -25,12 +25,19 @@ remoteowner=www-data    # Specify the owner of the file on the remove server. If
 logdir=~/make-logs    # Where to put the build logs? Leave blank to disable logging.
 logfile=$D.log    # Log file name. Normally you don't need to change it. Leave blank to disable logging
 buildlog=buildlog-$(date +%Y%m%d-%H%M%S).log    # Build log file name. All outputs from the compiling process will be logged here. Leave blank to disable logging.
-cleanevery=4    # Do 'make clean' every X times. This is to avoid building too many targets causing the disk being filled up, and build fails. Leave blank to disable this feature. Default: 4
+cleanevery=2    # Do 'make clean' every X times. This is to avoid building too many targets causing the disk being filled up, and build fails. Leave blank to disable this feature. Default: 4
 
 #############################################################
 # Doing the work.                                           #
 # Please don't modify the contents below, if not necessary. #
 #############################################################
+hash notify-send 2> /dev/null
+if [ $? -eq 0 ]; then
+  notification="enabled"
+else
+  notification="disabled"
+fi
+
 if [ -d $workdir ]; then
 #  devices=$(cat $workdir/vendor/aokp/vendorsetup.sh | sed 's/add_lunch_combo aokp_//g' | sed 's/-userdebug//g')
   devices=$(ls -1 $workdir/vendor/aokp/products/ | cut -d. -f1)
@@ -178,6 +185,7 @@ fi
 if [ ! -z $OUT_DIR_COMMON_BASE ]; then
   echo "Build output directory has been redirected to: $OUT_DIR_COMMON_BASE" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
 fi
+echo "On-screen notification is $notification\."
 sleep 5
 
 cd $workdir
@@ -211,15 +219,27 @@ for target in $buildtargets; do
     fi
     brunch $target 2>&1 | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
     if [ ${PIPESTATUS[0]} -ne 0 ]; then
-      echo "Build error. Please check log." | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
+      echo "Build error. Please check log. Current target: $target" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
       echo "Time wasted: $(timeconv $(($(date +%s) - singlestart)))" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
+      if [ $notification = "enabled" ]; then
+        notify-send "Build error. Please check log. Current target: $target
+        Time wasted: $(timeconv $(($(date +%s) - singlestart)))"
+      fi
       if [ -z $success ]; then
         echo "Failed the first time. Aborting." | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
+      if [ $notification = "enabled" ]; then
+        notify-send "Failed the first time. Aborting."
+      fi
         exit 1
       else
         echo "At least one target was being built successfully." | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
         echo "Build process will continue." | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
         echo "Successful targets: $success" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
+      if [ $notification = "enabled" ]; then
+        notify-send "At least one target was being built successfully.
+        Build process will continue.
+        Successful targets: $success"
+      fi
         failed="$failed $target"
       fi
     else
@@ -256,13 +276,26 @@ total=$((stop - start))
 
 if [ -z $failed ]; then
   echo -e "Everything built fine.\n" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
-  echo -e "These targets were built successfully: $success\n" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
+  echo -e "These targets were built: $success\n" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
+  if [ $notification = "enabled" ]; then
+    notify-send "Everything built fine.
+    These targets were built:
+    $success"
+  fi
 else
   echo -e "Some of the targets failed to build.\n" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
-  echo -e "These targets were built successfully: $success\n" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
+  echo -e "These targets were built: $success\n" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
   echo -e "These targets failed: $failed\n" | ( [ "$nolog" != "true" ] && tee -a $logdir/$buildlog || tee )
+  if [ $notification = "enabled" ]; then
+    notify-send "Some of the targets failed to build.
+    These targets were built: $success
+    These targets failed: $failed"
+  fi
 fi
 echo -e "Total time: $(timeconv $total)\n" | ( [ "$nolog" != "true" ] && tee -a $logdir/$logfile || tee )
+if [ $notification = "enabled" ]; then
+  notify-send "Total time: $(timeconv $total)"
+fi
 
 if [ "$nolog" != "true" ]; then
   cat $logdir/$logfile
